site_name: Documentación en MkDocs
# repo_url: https://github.com/username/mkdocs-documentation/
site_description: MkDocs documentation website.
site_author: Facultad de Informática de A Coruña
copyright: 2023 Universidad de La Coruña. Todos los derechos reservados.
docs_dir: docs


nav: 
  - 'Inicio': index.md
  - 'Configuración básica': 'mk_basics.md'
  - 'Importar documentación': 'mk_documentation.md'
  - 'Temas': 'mk_themes.md'
  - Material for MkDocs:
    - Configuración básica: 
      - Colores: mat_conf/mat_conf_colors.md
      - Fuentes: mat_conf/mat_conf_fonts.md
      - Lenguajes: mat_conf/mat_conf_lang.md
      - Búsqueda: mat_conf/mat_conf_search.md
      - Versionado: mat_conf/mat_conf_versions.md
    - 'Elementos funcionales':
      - Admonitions: mat_ele/mat_ele_admonitions.md
      - Anotaciones: mat_ele/mat_ele_annotations.md
      - Bloques de código: mat_ele/mat_ele_codeblocks.md
      - Pestañas de contenido: mat_ele/mat_ele_content_tabs.md
      - Diagramas: mat_ele/mat_ele_diagrams.md
  - Otras funcionalidades:
    - Jupyter Notebooks: other/jupyter_notebooks_example.ipynb
theme:
  name: material
  language: es
  features:
    - content.code.copy

  icon:
    annotation: material/plus-circle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Cambiar a modo claro

  font:
    text: Montserrat
    code: Montserrat Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

plugins:
    - mkdocs-jupyter
    - search

